### ISSUE TITLE
HTML Preview

### ISSUE THREAD

**Issue by wizston** [rhukhi/To-do-list#1]
Your index.html page isn't valid.

**Comment by rhukhi** [comment]
Good day,

I trust that this mail meets you well.

I have posted it on git. I tried to understand the JavaScript. I did but it
didn't work for my program.

I did my best in rewriting the code but it might not run.

Thank you for your time. I really appreciate it.

Kind Regards,
Ujara Rukky.

**Comment by wizston** [comment]
Okay good, i just checked... I will get back to everyone on/before Monday.

Cheers!

**Comment by rhukhi** [comment]
Okay sir. Thank you so muvh for the opportunity. I really appreciate it.
